[project]
name = "diy-project"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[tool.pytest.ini_options]
python_files = ["gen_test_*.py"]
asyncio_mode = "auto"

[tool.ruff]
exclude = [".slash_diy/", "*/tests/discovered/"]

[tool.ty.src]
exclude = [".slash_diy/", "*/tests/discovered/"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",         #
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.8",
    "ty>=0.0.27",
]
